package KieRule;
import com.ruleengine.droolengine.model.Order;

rule "HDFC"
when
    orderObject: Order(cardType == "HDFC", price > 10000)
then
    orderObject.setDiscount(10);
end

rule "ICICI"
when
    orderObject: Order(cardType == "ICICI", price > 15000)
then
    orderObject.setDiscount(8);
end

rule "SBI"
when
    orderObject: Order(cardType == "SBI", price > 15000)
then
    orderObject.setDiscount(15);
end
